kind: Deployment
apiVersion: apps/v1
metadata:
    name: mrdevops
spec:
    replicas: 1
    selector:      #tells the controller which pods to watch/belogs to
     matchLabels:
       app: mrdevops
    template:
        metadata:
          labels:
             app: mrdevops
        spec:
         containers:
           - name: mrdevops
             image: abhijitkale2025/pipeline_demo
             imagePullPolicy: Always
             ports:
             - containerPort: 80